models/cart.py
from db import db


class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    items = db.relationship('Item', backref='cart')
    delivery = db.relationship('Delivery', backref='cart', uselist=False)

models/category.py
from db import db


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), unique=True, nullable=False)
    image = db.Column(db.String(5000))
    dishes = db.relationship('Dish', backref='category')

models/user.py
from db import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(25), unique=True, nullable=False)
    password = db.Column(db.String(20), nullable=False)
    first_name = db.Column(db.String(25))
    last_name = db.Column(db.String(25))
    email = db.Column(db.String(30))
    is_staff = db.Column(db.Boolean, default=False)
    carts = db.relationship('Cart', backref='user')

controllers/user.py
from flask import render_template, url_for, request, redirect
from flask_login import login_user, current_user, login_required, logout_user
from db import db
from models.cart import Cart
from models.category import Category
from models.delivery import Delivery
from models.dish import Dish
from models.user import User
from models.item import Item


def login():
    if current_user.is_authenticated:
        return redirect(url_for('homepage'))
    if request.method == 'POST':
        user = User.query.filter_by(username=request.form['username']).first()
        if user != None and user.is_staff == False:
            if user.password == request.form['password']:
                login_user(user)
                return redirect(url_for('homepage'))
            else:
                return 'Wrong password'
        else:
            return 'User not found'
    return render_template('users/login.html')


def signup():
    if request.method == 'POST':
        try:
            if request.form['password'] == request.form['password_confirm']:
                new_user = User(
                    username=request.form['username'],
                    password=request.form['password'],
                    first_name=request.form['first_name'],
                    last_name=request.form['last_name'],
                    email=request.form['email']
                )
                db.session.add(new_user)
                db.session.commit()
            return redirect(url_for('homepage'))
        except Exception as e:
            return redirect(url_for('homepage'))
    return render_template('users/signup.html')


@login_required
def edit():
    if current_user.is_staff == True:
        return redirect(url_for('admins.admin_login'))
    id = current_user.id
    user = User.query.get(id)
    if request.method == 'POST':
        user.password = request.form['password']
        user.first_name = request.form['first_name']
        user.last_name = request.form['last_name']
        user.email = request.form['email']
        db.session.commit()
        return redirect(url_for('users.user'))
    return render_template('users/edit.html')


@login_required
def logout():
    logout_user()
    return redirect(url_for('homepage'))


def category(id):
    category = Category.query.get(id)
    if request.method == 'POST':
        if current_user.is_staff == True:
            return redirect(url_for('admins.admin_login'))
        cart = Cart.query.filter_by(
            user_id=current_user.id, delivery=None).first()
        if cart:
            item = Item.query.filter_by(
                dish_id=request.form['dish'], cart_id=cart.id).first()
            if item:
                item.amount += int(request.form['amount'])
            else:
                item = Item(
                    dish_id=request.form['dish'],
                    amount=request.form['amount']
                )
                cart.items.append(item)
        else:
            new_cart = Cart(user_id=current_user.id)
            item = Item(
                dish_id=request.form['dish'],
                amount=request.form['amount']
            )
            new_cart.items.append(item)
            db.session.add(new_cart)
        db.session.commit()
    return render_template('users/category.html', category=category)


@login_required
def user():
    if current_user.is_staff == True:
        return redirect(url_for('admins.admin_login'))
    return render_template('users/user.html')


@login_required
def history():
    if current_user.is_staff == True:
        return redirect(url_for('admins.admin_login'))
    deliveries = Delivery.query.join(Cart).filter(
        Cart.user_id == current_user.id).all()
    dishes = Dish.query.all()
    summary = 0
    for delivery in deliveries:
        for item in delivery.cart.items:
            for dish in dishes:
                if dish.id == item.dish_id:
                    summary += item.amount*dish.price
    return render_template('users/history.html', deliveries=deliveries, dishes=dishes, summary=summary)


@login_required
def cart(id):
    if current_user.is_staff == True:
        return redirect(url_for('admins.admin_login'))
    cart = Cart.query.filter_by(
        user_id=id, delivery=None).first()
    dishes = Dish.query.all()
    if request.method == 'POST':
        item = Item.query.filter_by(id=request.form['item']).first()
        db.session.delete(item)
        db.session.commit()
    summary = 0
    if cart != None:
        for item in cart.items:
            for dish in dishes:
                if dish.id == item.dish_id:
                    summary += item.amount*dish.price
    return render_template('users/cart.html', cart=cart, dishes=dishes, summary=summary)


@login_required
def show_delivery(id):
    if current_user.is_staff == True:
        return redirect(url_for('admins.admin_login'))
    delivery = Delivery.query.get(id)
    dishes = Dish.query.all()
    summary = 0
    for item in delivery.cart.items:
        for dish in dishes:
            if dish.id == item.dish_id:
                summary += item.amount*dish.price
    return render_template('users/show_delivery.html', delivery=delivery, dishes=dishes, summary=summary)


@login_required
def order(id):
    if current_user.is_staff == True:
        return redirect(url_for('admins.admin_login'))
    cart = Cart.query.filter_by(
        id=id, delivery=None).first()
    if request.method == 'POST':
        new_delivery = Delivery(
            address=request.form['address'],
            comment=request.form['comment'],
            cart_id=id,
        )
        db.session.add(new_delivery)
        db.session.commit()
        return redirect(url_for('users.show_delivery', id=new_delivery.id))
    return render_template('users/order.html', cart=cart)

routes/users.py
from flask import Blueprint
from controllers.user import login, signup, logout, category, user, history, cart, show_delivery, order, edit

users_bp = Blueprint('users', __name__)

users_bp.add_url_rule('/login', view_func=login, methods=['GET', 'POST'])
users_bp.add_url_rule('/signup', view_func=signup, methods=['GET', 'POST'])
users_bp.add_url_rule('/user/edit', view_func=edit, methods=['GET', 'POST'])
users_bp.add_url_rule('/logout', view_func=logout)
users_bp.add_url_rule('/category/<int:id>',
                      view_func=category, methods=['GET', 'POST'])
users_bp.add_url_rule('/user', view_func=user)
users_bp.add_url_rule('/user/history', view_func=history)
users_bp.add_url_rule('/user/<int:id>/cart',
                      view_func=cart, methods=['GET', 'POST'])
users_bp.add_url_rule('/user/order/<int:id>',
                      view_func=order, methods=['GET', 'POST'])
users_bp.add_url_rule('/user/show_delivery/<int:id>', view_func=show_delivery)

templates/users/cart.html
{% extends 'layout.html'%} {% block content %} {% if cart==None %}
<h1>Your Cart Is Empty !</h1>
{% else %} {% if summary!=0 %}
<div>
  <a
    href="{{url_for('users.order',id=cart.id)}}"
    class="btn waves-effect waves-light"
    >Order</a
  >
</div>
<div>
  <h3 class="blue-text text-darken-2">Order Summary - {{summary}} $</h3>
</div>
{% else %}
<h1>Your Cart Is Empty !</h1>
{% endif %}
<table>
  {% if summary!=0 %}
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Amount</th>
      <th>Total Dish Price</th>
      <th></th>
    </tr>
  </thead>
  {% endif %}
  <tbody>
    <form action="{{url_for('users.cart',id=cart.user_id)}}" method="POST">
      {% for item in cart.items %} {% for dish in dishes %} {% if
      dish.id==item.dish_id %}
      <tr>
        <td>{{dish.name}}</td>
        <td>{{dish.price}} $</td>
        <td>{{item.amount}}</td>
        <td>{{item.amount*dish.price}} $</td>
        <td>
          <button
            class="btn waves-effect waves-light"
            type="submit"
            name="item"
            value="{{item.id}}"
            class="secondary-content waves-effect waves-teal btn-flat"
          >
            Delete
          </button>
        </td>
      </tr>
      {% endif %} {% endfor %} {% endfor %}
    </form>
  </tbody>
</table>
{% endif %}{% endblock %}

templates/users/category.html
{% extends 'layout.html'%} {% block content %}
<div class="container">
  <h1 class="blue-text text-darken-2">{{category.name}}</h1>
  <div class="row">
    {% for dish in category.dishes %}
    <div class="col s4">
      <div>
        <img src="{{dish.image}}" width="200" height="200" />
      </div>
      <div>
        <h3>{{dish.name}}</h3>
      </div>
      <p>{{dish.description}}</p>
      {% if dish.is_gluten_free%}
      <h4>Gluten Free</h4>
      {% endif %} {% if dish.is_vegeterian%}
      <h4>Vegeterian</h4>
      {% endif %}
      <h3>Price {{dish.price}} $</h3>
      {% if current_user.is_authenticated %}
      <form action="{{url_for('users.category',id=category.id)}}" method="POST">
        <div class="input-field col s12">
          <select name="amount">
            <option value="1" selected>1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
          </select>
        </div>
        <button
          class="btn waves-effect waves-light"
          type="submit"
          name="dish"
          value="{{dish.id}}"
          class="secondary-content waves-effect waves-teal btn-flat"
        >
          add
        </button>
      </form>
      {% endif %}
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/users/edit.html
{% extends 'layout.html'%} {% block content %}

<form action="{{url_for('users.edit')}}" method="POST">
  <div>
    Password
    <input type="password" name="password" value="{{current_user.password}}" />
  </div>
  <div>
    Confirm Password
    <input
      type="password"
      name="password_confirm"
      value="{{current_user.password}}"
    />
  </div>
  <div>
    First Name
    <input
      type="text"
      name="first_name"
      value="{{current_user.first_name}}"
      pattern="[a-zA-Z ]+"
      required
    />
  </div>
  <div>
    Last Name
    <input
      type="text"
      name="last_name"
      value="{{current_user.last_name}}"
      pattern="[a-zA-Z ]+"
      required
    />
  </div>
  <div>
    Email
    <input type="email" name="email" value="{{current_user.email}}" required />
  </div>
  <button class="btn waves-effect waves-light" type="submit">Edit Info</button>
</form>

{% endblock %}

templates/users/history.html
{% extends 'layout.html'%} {% block content %}
<h1>Orders History of {{current_user.username}}</h1>
{% for delivery in deliveries %}{% if summary!=0 %}
<h5>Delivery ID - {{delivery.id}}</h5>
<h5>Order Summary - {{summary}} $</h5>
<h5>Order Date - {{ delivery.created.strftime('%d/%m/%Y - %H:%M:%S') }}</h5>
{% if delivery.is_delivered %}
<h6 class="blue-text text-darken-2">Delivered</h6>
{%else%}
<h6 class="blue-text text-darken-2">Not Delivered Yet</h6>
{% endif %}{% endif %}
<table>
  {% if summary!=0 %}
  <thead>
    <tr>
      <th>Dish Name</th>
      <th>Price</th>
      <th>Amount</th>
      <th>Total Dish Price</th>
    </tr>
  </thead>
  <tbody>
    {% for item in delivery.cart.items %} {% for dish in dishes %} {% if
    dish.id==item.dish_id %}
    <tr>
      <td>{{dish.name}}</td>
      <td>{{dish.price}} $</td>
      <td>{{item.amount}}</td>
      <td>{{item.amount*dish.price}} $</td>
    </tr>
    {% endif %} {% endfor %} {% endfor %}
  </tbody>
</table>
{% endif %}{% endfor %} {% endblock %}

templates/users/login.html
{% extends 'layout.html'%} {% block content %}
<form action="{{url_for('users.login')}}" method="POST">
  <div class="input-field col s6">
    <input type="text" name="username" placeholder="Username" />
  </div>
  <div class="input-field col s6">
    <input type="password" name="password" placeholder="Password" />
  </div>
  <div><ul>
    <li>
    <button class="btn waves-effect waves-light" type="submit">Login</button>
    </li>
    <br>
    <br>
    </form>
    <li><a href="{{url_for('admins.admin_login')}}" class="btn waves-effect waves-light"
    >Admin Only</a></li>
  </ul></div>
{% endblock %}

templates/users/order.html
{% extends 'layout.html'%} {% block content %}
<h3>Please Fill Details For Delivery</h3>
<form action="{{url_for('users.order',id=cart.id)}}" method="POST">
  <ul>
    <li><input type="text" name="address" placeholder="Address" required /></li>
    <li><input type="text" name="comment" placeholder="Comment" /></li>
    <button class="btn waves-effect waves-light" type="submit">Order</button>
  </ul>
</form>
{% endblock %}

templates/users/show_delivery.html
{% extends 'layout.html'%} {% block content %}
<h3>Your Delivery Is On It's Way !</h3>

<h6>Delivery ID - {{delivery.id}}</h6>
<h6>Order Time - {{delivery.created.strftime('%d/%m/%Y - %H:%M:%S')}}</h6>
<h6>Order Summary - {{summary}} $</h6>

<br />
<br />

<table>
  <thead>
    <tr>
      <th>Dish Name</th>
      <th>Price</th>
      <th>Amount</th>
    </tr>
  </thead>

  <tbody>
    {% for item in delivery.cart.items %} {% for dish in dishes %} {% if
    dish.id==item.dish_id %}
    <tr>
      <td>{{dish.name}}</td>
      <td>{{dish.price}} $</td>
      <td>{{item.amount}}</td>
    </tr>
    {% endif %} {% endfor %} {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/users/signup.html
{% extends 'layout.html'%} {% block content %}
<form action="{{url_for('users.signup')}}" method="POST">
  <div><input type="text" name="username" placeholder="Username" /></div>
  <div>
    <input type="password" name="password" placeholder="Password" />
  </div>
  <div>
    <input
      type="password"
      name="password_confirm"
      placeholder="Confirm Password"
    />
  </div>
  <div>
    <input
      type="text"
      name="first_name"
      placeholder="First Name"
      pattern="[a-zA-Z ]+"
      required
    />
  </div>
  <div>
    <input
      type="text"
      name="last_name"
      placeholder="Last Name"
      pattern="[a-zA-Z ]+"
      required
    />
  </div>
  <div>
    <input type="email" name="email" placeholder="Email" required />
  </div>
  <button class="btn waves-effect waves-light" type="submit">Sign Up</button>
</form>
{% endblock %}

templates/users/user.html
{% extends 'layout.html'%} {% block content %}

<div class="container"></div>
<h4>Username - {{current_user.username}}</h4>
<h4>First Name - {{current_user.first_name}}</h4>
<h4>Last Name - {{current_user.last_name}}</h4>
<h4>Email - {{current_user.email}}</h4>

<a href="{{url_for('users.history')}}" class="btn waves-effect waves-light"
  >Orders History</a
>
<a href="{{url_for('users.edit')}}" class="btn waves-effect waves-light"
  >Edit Info</a
>
</div>
{% endblock %}